baseURL = 'https://shift1w.com/'
title = 'Jacob Wiseberg'
languageCode = 'en-us'
copyright = 'Jacob Wiseberg'

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  baseName = "blog"

[params]
  description = 'Personal blog and portfolio'
  author = 'Jacob Wiseberg'
